config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  resources :styles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'breweries#index'
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only: [:index, :show]
  post 'places', to:'places#search'

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :users do
    post 'toggle_closed', on: :member
  end

  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'
end

app/models/beer_club.rb
class BeerClub < ApplicationRecord
  has_many :memberships
  has_many :users, through: :memberships
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :ensure_that_is_admin, only: [:destroy]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all

    order = params[:order] || 'name'

    @beer_clubs = case order
                  when 'name' then @beer_clubs.sort_by(&:name)
                  when 'founded' then @beer_clubs.sort_by(&:founded)
                  when 'city' then @beer_clubs.sort_by(&:city)
                  end
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @membership = Membership.new
    @membership.beer_club = @beer_club
    if current_user && current_user.memberships.find_by(beer_club: @beer_club.id)
      @membership = Membership.find_by(user: current_user.id, beer_club: @beer_club.id)
    end
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_beer_club
    @beer_club = BeerClub.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def beer_club_params
    params.require(:beer_club).permit(:name, :founded, :city)
  end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_with(model: beer_club, local: true) do |form| %>
  <% if beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% beer_club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :name, class:"col-sm-2 col-form-label" %>
    <div class="col-md-8">
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :founded, class:"col-sm-2 col-form-label" %>
    <div class="col-md-8">
      <%= form.number_field :founded, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :city, class:"col-sm-2 col-form-label" %>
    <div class="col-md-8">
      <%= form.text_field :city, class: "form-control" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing Beer Club</h1>

<%= render 'form', beer_club: @beer_club %>

<%= link_to 'Show', @beer_club %> |
<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/index.html.erb
<h1>Beer Clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th> <%= link_to 'Name', beer_clubs_path(order:"name") %> </th>
      <th> <%= link_to 'Founded', beer_clubs_path(order:"founded") %> </th>
      <th> <%= link_to 'City', beer_clubs_path(order:"city") %> </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= beer_club.name %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
        <td><%= link_to 'Show', beer_club %></td>
        <% if current_user %>
          <td><%= link_to 'Edit', edit_beer_club_path(beer_club) %></td>
          <td><%= link_to 'Destroy', beer_club, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>     
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to('New Beer Club', new_beer_club_path) if current_user %>

app/views/beer_clubs/new.html.erb
<h1>New Beer Club</h1>

<%= render 'form', beer_club: @beer_club %>

<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/show.html.erb
<h1><%= @beer_club.name %> <%= @beer_club.city %></h1>

<p>
  Founded <%= @beer_club.founded %>
</p>

<h2>Members</h2>

<ul>
  <% @beer_club.users.each do |user| %>
    <li><%= link_to user.username, user_path(user.id) %></li>
  <% end %>
</ul>

<% if current_user %>
  <% if not (@beer_club.memberships.exists?(:user_id => current_user.id)) %>
    <%= form_for(@membership) do |f| %>
      <%= f.hidden_field :beer_club_id %>
      <%= f.submit value:"join the club" %>
    <% end %>
  <% else %>
    <%= form_for(@membership, method: "delete") do |f| %>
      <%= f.hidden_field :beer_club_id %>
      <%= f.submit value: "end the membership" %>
    <% end %>
  <% end %>

  <%= link_to 'Edit', edit_beer_club_path(@beer_club) %>
  <%= link_to 'Destroy', @beer, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>