config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  resources :styles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'breweries#index'
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only: [:index, :show]
  post 'places', to:'places#search'

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :users do
    post 'toggle_closed', on: :member
  end

  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'
end

app/models/user.rb
class User < ApplicationRecord
  include RatingAverage

  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships
  has_secure_password

  validates :username, uniqueness: true,
                       length: { in: 3..30 }
  validates :password, length: { minimum: 4 },
                       format: { with: /\A(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).*\z/,
                                 message: "must contain a lowercase letter, an uppercase letter and a digit" }

  def self.create_oauth_user(username)
    password = SecureRandom.urlsafe_base64(6)
    User.create username: username, password: password
  end

  def self.top(amount)
    sorted_by_rating_in_desc_order = User.all.sort_by{ |u| -(u.ratings.count || 0) }
    sorted_by_rating_in_desc_order.take amount
  end

  def favorite_beer
    return nil if ratings.empty?

    ratings.order(score: :desc).limit(1).first.beer
  end

  def favorite_style
    favorite(:style)
  end

  def favorite_brewery
    favorite(:brewery)
  end

  def favorite(groupped_by)
    return nil if ratings.empty?

    grouped_ratings = ratings.group_by{ |r| r.beer.send(groupped_by) }
    averages = grouped_ratings.map do |group, ratings|
      { group: group, score: average_of(ratings) }
    end

    averages.max_by{ |r| r[:score] }[:group]
  end

  def average_of(ratings)
    ratings.sum(&:score).to_f / ratings.count
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_is_admin, only: [:toggle_closed]

  # GET /users
  # GET /users.json
  def index
    Beer.includes(:brewery, :style).all
    @users = User.includes(:beers, :ratings)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? && @user == current_user && @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    return unless @user == current_user

    @user.destroy
    reset_session
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_closed
    user = User.find(params[:id])
    user.update_attribute :closed, !user.closed

    new_status = user.closed? ? "closed" : "opened"

    redirect_to user, notice: "account of #{user.username} #{new_status}"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div class="field">
      <%= form.label :username %>
      <%= form.text_field :username %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password for <%= @user.username %></h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th> rated beers </th>
      <th> total ratings </th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
        <td>
          <% if user.closed and current_user and current_user.admin %>
            <span class="badge badge-info">account closed</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1><%= @user.username %>
<% if @user.closed and current_user and current_user.admin %>
  <span class="badge badge-info">account closed</span>
<% end %>
</h1>

<% if current_user and current_user.admin %>
  <% if @user.closed %>  
    <p><%= link_to "open account", toggle_closed_user_path(@user.id), method: :post, class: "btn btn-warning" %></p>
  <% else %>
    <p><%= link_to "close account", toggle_closed_user_path(@user.id), method: :post, class: "btn btn-danger" %></p>
  <% end %>
<% end %>

<% if @user.ratings.empty? %>
  Has made no ratings yet
<% else %>
  Has made <%= pluralize(@user.ratings.size, 'rating') %>, average <%= round(@user.average_rating) %>
<% end %>

<% if @user.favorite_style %>
  <p>Favorite style is <%= @user.favorite_style %></p>
<% end %>

<% if @user.favorite_brewery %>
  <p>Favorite brewery is <%= @user.favorite_brewery.name %></p>
<% end %>

<% if @user.beer_clubs.empty? %>
  <p>Not a member in any clubs</p>
<% else %>
  <p>Member of</p>
  <ul>
    <% @user.beer_clubs.each do |beer_club| %>
      <li><%= link_to beer_club.name, beer_club %></li>
    <% end %>
  </ul>
<% end %>

<h2>Ratings</h2>

<ul class="list-group">
  <% @user.ratings.each do |rating| %>
    <li class="list-group-item col col-md-3 py-2"> <%= rating %> 
      <% if @user == current_user %>
        <%= link_to 'delete', rating, method: :delete, data: { confirm: 'are you sure?' } %>
      <% end %>
    </li>
  <% end %>
</ul>

<% if @user == current_user %>
  <%= link_to 'Edit', edit_user_path(@user), class:'btn btn-primary' %>
  <%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %>
<% end %>